# Generated by Django 3.0.6 on 2020-07-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.ManyToManyField(related_name='exercises', to='log_app.MuscleGroup'),
        ),
    ]
