# Generated by Django 3.0.6 on 2020-07-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0003_auto_20200716_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='weight_lifted',
            field=models.CharField(max_length=200),
        ),
    ]
