# Generated by Django 3.0.6 on 2020-07-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0006_auto_20200717_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
    ]
